import { persona as suiri } from './suiri.js';
import { persona as bannin } from './bannin.js';
import { persona as kanjou } from './kanjou.js';
import { persona as sokkyou } from './sokkyou.js';
import { persona as ura } from './ura.js';
import { persona as toubou } from './toubou.js';
import { persona as ayatsuri } from './ayatsuri.js';
import { persona as gyakuten } from './gyakuten.js';
import { persona as mikiri } from './mikiri.js';
import { persona as shoshinsha } from './shoshinsha.js';
export const personas = { suiri, bannin, kanjou, sokkyou, ura, toubou, ayatsuri, gyakuten, mikiri, shoshinsha };
