import { modal, finish, stateOf, has } from '../common.js'; import { inferenceFinal } from '../../data/parts/inference-final.js';
export function canBreak(node, cards, bravado=false, uno=false) { const required=node.requirements.map(g=>g.filter(x=>cards.includes(x))); const count=required.reduce((n,g)=>n+(g.length?1:0),0); const needed=Math.max(1,node.requirements.length+(bravado?1:0)-(uno&&['n8','n9','n10','n11'].includes(node.id)?1:0)); return count>=needed; }
export const B1_AGITATION_THRESHOLD=97;
export const BRAVADO_AGITATION_THRESHOLD=50;
export function isB1Open(agitation) { return agitation>=B1_AGITATION_THRESHOLD; }
export function triggersBravado(agitation, threshold=BRAVADO_AGITATION_THRESHOLD) { return agitation>=threshold; }
export function isB2Locked(node,cards){return node.id==='n10'&&!cards.includes('acrostic')&&!cards.includes('acrostic_card');}
export const jointReasoning={async start(ctx,args={}){const data=args.debugData||inferenceFinal,s=stateOf(ctx),cards=[...(s.items||[]),...Object.values(s.flags||{}).flat()];return new Promise(resolve=>{const m=modal(ctx,args.variant==='a4'?'推理ショー乗っ取り':'壁の内の作者');let broken=[],effects=[],agitation=s.params?.agitation||0,bravado=false,uno=false;// A-4 は自白の入口だけを自分で暴く短い推理ショーにする。
const nodes=data.phases.flatMap(p=>p.nodes).filter(n=>args.variant!=='a4'||n.id==='n1');
const gateStatus=()=>isB1Open(agitation)?'真相の門：開いた':`真相の門：まだ崩せていない（あと${B1_AGITATION_THRESHOLD-agitation}）`;
const render=()=>{const available=nodes.filter(n=>!broken.includes(n.id));m.main.innerHTML=`<div class="agitation">動揺 <b>${agitation}</b><i><em style="width:${agitation}%"></em></i><small>${gateStatus()}</small></div><p>${agitation>=80?'宗玄「お前が――」':agitation>=60?'宗玄「君は、何を…」':'宗玄「証明してみたまえ」'}</p><div class="node-grid">${available.map(n=>`<div class="parts-option"><button data-id="${n.id}"><small>${n.phase}</small>${n.id.toUpperCase()}　${n.claim}</button>${n.note?`<small class="option-note">${n.note}</small>`:''}</div>`).join('')}</div><p class="parts-note">${bravado?'開き直りモード：要求カードが一段厳しい。':''}${uno?' 宇野が同席し、後半の要求が緩和されている。':''}</p>`;m.main.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>respond(available.find(n=>n.id===b.dataset.id)));};
const respond=n=>{if(isB2Locked(n,cards)){effects.push({t:'log',key:'joint_reasoning',value:'b2_locked'});return ending('b2_unfinished','折句がない。証明のない物語は、妄想と言う。');}const own=canBreak(n,cards,bravado,uno);m.main.innerHTML=`<p class="claim">宗玄「${n.claim}」</p><div class="parts-actions"><button id="own" ${own?'':'disabled'}>自分が暴く（カード提示）</button>${n.conanProxy?'<button id="proxy">コウナンに任せる<small>宗玄は動じない</small></button>':''}${n.relicBonus?'<button id="relic">律の遺したものを突きつける 🕯</button>':''}</div><button id="back">戻る</button>`;m.main.querySelector('#back').onclick=render;if(own)m.main.querySelector('#own').onclick=()=>win(n,1);if(n.conanProxy)m.main.querySelector('#proxy').onclick=()=>win(n,0);if(n.relicBonus)m.main.querySelector('#relic').onclick=()=>win(n,2);};
const win=(n,mult)=>{broken.push(n.id);const delta=n.agitation*mult;agitation=Math.min(100,agitation+delta);if(delta)effects.push({t:'param',key:'agitation',delta});if(!bravado&&triggersBravado(agitation,data.bravado?.threshold))bravado=true;if(n.id==='n6'){uno=true;effects.push({t:'log',key:'uno_present',value:true});}if(args.variant==='a4'){effects.push({t:'item',id:'confession_record'});effects.push({t:'log',key:`a4_confession_${n.id}`,value:true});}if(!nodes.some(x=>!broken.includes(x.id))) final(); else render();};
const final=()=>{const incomplete='証明は揃った。だが、崩れたのは宗玄ではなく、証明の順番だけだった。栞の言葉は、まだ彼の結末を越えられない。';m.main.innerHTML=`<p class="claim">【BGM消音】六番の唄</p><p>宗玄「作者にも、もう変えられん」</p>${args.variant==='a4'?'':`<p class="parts-note">${gateStatus()}</p>`}<div class="parts-actions">${data.final.choices.filter(c=>!c.requires||has(ctx,c.requires)).map(c=>`<button data-e="${c.ending}" data-id="${c.id}">${c.label}</button>`).join('')}</div>`;m.main.querySelectorAll('[data-e]').forEach(b=>b.onclick=()=>ending(b.dataset.id==='meaning'&&args.variant!=='a4'&&!isB1Open(agitation)?'b2_unfinished':b.dataset.e,b.dataset.id==='meaning'&&args.variant!=='a4'&&!isB1Open(agitation)?incomplete:b.dataset.id==='meaning'?data.final.trueText:''));};
const complete=(endingId)=>{effects.push({t:'log',key:'joint_reasoning',value:endingId});effects.push({t:'log',key:'ending_hint',value:endingId});finish(m.root,resolve,{effects,endingId,agitation,bravado,broken});};const ending=(endingId,text)=>{m.main.innerHTML=`<h2>${endingId==='b1_true'?'B-1 真相END':'B-2 未完END'}</h2><p class="result-text">${text}</p><button id="done">対峙を終える</button>`;m.main.querySelector('#done').onclick=()=>complete(endingId);};m.close.onclick=()=>complete('b2_unfinished');render();});}};
